version: '3'

services:
  externalstructureproxy:
    networks:
      - default
      - nginx-net
    environment:
      VIRTUAL_HOST: gnps-external.ucsd.edu
      VIRTUAL_PORT: 5010
      LETSENCRYPT_HOST: gnps-external.ucsd.edu
      LETSENCRYPT_EMAIL: miw023@ucsd.edu
      command: /app/run_production_server.sh

networks:
  nginx-net:
    external:
      name: nginx-net